# Workaround for https://github.com/gazebosim/gz-rendering/pull/1175
# As the removed functions are inline, see https://github.com/llvm/llvm-project/commit/aeecef08c385b1e4955155dd649a2d3724463849
# we can continue to temporary use clang 18 and use a newer libc++ version at runtime
c_compiler_version:            # [osx]
  - 18                         # [osx]
cxx_compiler_version:          # [osx]
  - 18                         # [osx]
